spring:
  main:
    web-application-type: none
    banner-mode: off

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    io:
      steviemul:
        patch: INFO